site_name: UMLARS Translator
site_author: Filip Pawłowski

repo_name: umlars-translator
repo_url: https://github.com/UMLI-Organization/umlars-translator

nav:
  - UML Interpreter: index.md
  - Features: features.md
  - Code Reference:
      - Reference - library code: code_reference/reference.md
      - Deserializer: code_reference/deserializer_reference.md
  - PyPI package 🔗: 'https://pypi.org/project/umlars_translator/'

theme:
  name: material
  analytics:
    gtag: G-ABC123
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/diagram-project
    favicon: material/library
    repo: fontawesome/brands/gitlab

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
