import os


# LOGGER
APP_LOGGER_NAME = "MESSAGING_LOGGER"
LOG_LEVEL = os.getenv("MESSAGING_LOG_LEVEL", "DEBUG")
LOG_FILE = os.getenv("MESSAGINGE_LOG_FILE", "logs/umlars-messaging.log")


# RABBITMQ
MESSAGE_BROKER_PORT = int(os.getenv("RABBITMQ_NODE_PORT", 5672))
MESSAGE_BROKER_USER = os.getenv("RABBITMQ_DEFAULT_USER", "admin")
MESSAGE_BROKER_PASSWORD = os.getenv("RABBITMQ_DEFAULT_PASS", "admin")
MESSAGE_BROKER_PREFETCH_COUNT = 100
