from enum import Enum


class DiagramType(Enum):
    """Enum class for diagram types"""

    CLASS = "Class"
    USE_CASE = "UseCase"
    ACTIVITY = "Activity"
    SEQUENCE = "Sequence"
    STATE = "State"
    COMPONENT = "Component"
    DEPLOYMENT = "Deployment"
    OBJECT = "Object"
    COMMUNICATION = "Communication"
    TIMING = "Timing"
    INTERACTION_OVERVIEW = "InteractionOverview"
    CUSTOM = "Custom"
    NONE = "None"


class PrimitiveTypes(Enum):
    """Enum class for primitive types"""

    STRING = "String"
    INTEGER = "Integer"
    BOOLEAN = "Boolean"
    REAL = "Real"
    UNLIMITED_NATURAL = "UnlimitedNatural"
    VOID = "Void"
    ANY = "Any"


class UmlElementType(Enum):
    """Enum class for UML element types"""

    PACKAGE = "Package"
    CLASS = "Class"
    INTERFACE = "Interface"
    ENUMERATION = "Enumeration"
    PRIMITIVE_TYPE = "PrimitiveType"
    DATA_TYPE = "DataType"
    SIGNAL = "Signal"
    ARTIFACT = "Artifact"
    COMPONENT = "Component"
    COLLABORATION = "Collaboration"
    NODE = "Node"
    USE_CASE = "UseCase"
    ACTOR = "Actor"
    ACTIVITY = "Activity"
    STATE = "State"
    INTERACTION = "Interaction"
    INTERACTION_FRAGMENT = "InteractionFragment"
    LIFELINE = "Lifeline"
    MESSAGE = "Message"
    EXECUTION_SPECIFICATION = "ExecutionSpecification"
    INTERACTION_USE = "InteractionUse"
    DEPLOYMENT_SPECIFICATION = "DeploymentSpecification"
    DEPLOYMENT_TARGET = "DeploymentTarget"
    DEPLOYMENT = "Deployment"
    ARTIFACT_INSTANCE = "ArtifactInstance"
    COMPONENT_INSTANCE = "ComponentInstance"
    NODE_INSTANCE = "NodeInstance"
    ACTOR_INSTANCE = "ActorInstance"
    USE_CASE_INSTANCE = "UseCaseInstance"
    STATE_MACHINE = "StateMachine"
    STATE_MACHINE_STATE = "StateMachineState"
    ASSOCIATION = "Association"
    DEPENDENCY = "Dependency"
    GENERALIZATION = "Generalization"
    REALIZATION = "Realization"